name: Docker Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t ecommerce-app .

      - name: Run Docker container
        run: docker run -d --name my_django_app ecommerce-app

      - name: Run tests
        run: docker exec my_django_app sh -c "cd store && python tests.py"

      - name: Stop and remove container
        if: ${{ always() }}
        run: |
          docker stop my_django_app
          docker rm my_django_app
